import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingScreenIcon: {
    height: 100,
    width: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingScreenSpinner: {
    marginVertical: 10,
  },
  itemsLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerText: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingLeft: 28,
  },
  headerIcon: {
    marginHorizontal: 10,
    marginTop: 10,
  },
  rightSwipeContainer: {
    flexDirection: 'row',
    width: 120,
    justifyContent: 'space-between',
  },
  swipeButton: {
    width: 60,
    backgroundColor: '#dee2e6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  input: {
    height: 50,
    width: 150,
    margin: 12,
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
  },
  boxInput: {
    height: 50,
    width: 170,
    marginLeft: 24,
    marginVertical: 20,
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
  },
  boxDisabledButton: {
    backgroundColor: '#ccc',
  },
  boxButton: {
    padding: 10,
    borderRadius: 5,
    marginRight: 24,
  },
  boxSaveText: {
    fontFamily: 'Avenir-Book',
    fontSize: 14,
    color: 'black',
  },
  whiteText: {
    color: 'white',
  },
  selectedWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  itemsList: {
    marginBottom: 75,
  },
  item: {
    borderWidth: 0.2,
    borderColor: '#ddd',
    paddingHorizontal: 25,
    paddingVertical: 12,
    backgroundColor: '#f8f9fa',
    flexDirection: 'row',
    alignItems: 'center',
    height: 70,
  },
  itemTextContainer: {
    flex: 1,
    justifyContent: 'center',
    marginLeft: 12,
  },
  itemText: {
    fontSize: 18,
    fontFamily: 'Avenir-Book',
  },
  remainingDaysText: {
    fontSize: 16,
    fontFamily: 'Avenir-Book',
  },
  itemImage: {
    width: 50,
    height: '100%',
    resizeMode: 'contain',
  },
  fabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    bottom: 0,
    width: '100%',
    // paddingHorizontal: 10,
    paddingBottom: 8,
    backgroundColor: 'white',
  },
  fabButton: {
    flex: 1,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1b4965',
    borderRadius: 8,
    marginHorizontal: 2,
  },
  fabButtonText: {
    fontSize: 17,
    color: 'white',
    fontFamily: 'Avenir-Book',
  },
  emptyFab: {
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1b4965',
    borderRadius: 28,
  },
  modalContent: {
    backgroundColor: 'white',
    marginHorizontal: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    padding: 20,
    position: 'absolute',
    top: '15%',
    left: 0,
    right: 0,
  },
  modalHeader: {
    marginVertical: 10,
    fontFamily: 'Avenir-Book',
    fontSize: 20,
  },
  titleText: {
    fontSize: 20,
    fontFamily: 'Avenir-Book',
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 4,
  },
  categoriesContainer: {
    margin: 0,
    padding: 0,
    height: 50,
    paddingBottom: 0,
  },
  emptyStateContainer: {
    marginTop: 20,
    marginBottom: 80,
  },
  emptyStateContentContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    paddingHorizontal: 30,
    paddingBottom: 40,
  },
  emptyStateChefLogo: {
    height: 56,
    width: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  plusOne: {fontSize: 16, color: 'white'},
  scrollViewStyle: {
    marginHorizontal: 24,
    marginVertical: 10,
  },
  tab: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#F2F2F2',
    marginRight: 8,
  },
  selectedTab: {
    backgroundColor: '#D8D8D8',
    borderRadius: 12,
  },
  tabText: {
    fontSize: 13,
    color: '#333',
    fontFamily: 'Avenir-Book',
  },
  selectedTabText: {
    color: '#333',
  },
  button: {
    padding: 10,
    borderRadius: 5,
  },
  disabledButton: {
    backgroundColor: '#ccc',
  },
  actionItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  actionItemText: {
    fontSize: 20,
    fontFamily: 'Avenir-Book',
    lineHeight: 55,
    color: '#666',
    marginLeft: 10,
  },
  saveText: {
    fontFamily: 'Avenir-Book',
    fontSize: 14,
    color: 'black',
  },
  loadingText: {
    fontFamily: 'Avenir-Book',
    fontSize: 30,
    color: 'black',
  },
  singleAddItemContainer: {
    alignItems: 'left',
    padding: 100,
  },
  cancelButton: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  singleAddItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#f9f9f9',
  },
  singleAddItemList: {
    maxHeight: 250,
    borderColor: '#ccc',
    borderWidth: 1,
    marginBottom: 10,
  },
  singleAddItemIcon: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    marginRight: 10,
  },
  badReviewContainer: {
    alignItems: 'left',
    padding: 100,
    marginTop: 150,
  },
  reviewOptions: {
    marginVertical: 2,
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    width: '90%',
  },
});
